// rtcsocks-exit —— 命令行版 P2P SOCKS5 出口端（answerer）
//
// 无 WebSocket 信令：粘贴客户端(rtcsocks)生成的 OFFER，本程序生成 ANSWER
// 返回给客户端（可选写入 --answer-file），P2P 建立后作为出口，
// 按 SYN 帧真正对目标发起 TCP/UDP 连接（复用 Src/server 的出口实现）。
//
// 不修改、不影响旧 client/server。

#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <mutex>
#include <string>
#include <thread>
#include <unordered_map>
#include <vector>

#include <asio.hpp>
#include <plog/Log.h>

#include "crash_dump.h"
#include "is_std_in_terminal.h"
#include "manual_p2p.h"
#include "rtc_logger.h"
#include "session_mux.h"
#include "tunnel_session.h"

namespace
{

constexpr const char *kProgramName = "rtcsocks-exit";
constexpr const char *kVersion = "1.0.0";

constexpr int kDefaultThreadCount = 4;
constexpr int kDefaultWaitSec = 300; // 等待 OFFER 文件的默认超时
constexpr int kGatherTimeoutSec = 30;

std::atomic<bool> running{true};

void signal_handler(int)
{
    running = false;
}

struct Options
{
    std::string stun_host; // 为空则只用 host 候选（同一局域网/直连场景）
    uint16_t stun_port = 3478;
    int threads = kDefaultThreadCount;
    std::string offer_file;  // 从该文件读取 OFFER（代替 stdin 粘贴）
    std::string answer_file; // ANSWER 同时写入该文件
    int wait_sec = kDefaultWaitSec;
    rtc::LogLevel log_level = rtc::LogLevel::Info;
};

enum class ParseResult
{
    Ok,
    Handled, // 已处理 --help / --version，直接退出
    Error,
};

void printUsage(std::FILE *out)
{
    std::fprintf(out,
                 "%s %s -- P2P SOCKS5 exit side (manual SDP exchange, no signaling server)\n"
                 "\n"
                 "Usage:\n"
                 "  %s [options]\n"
                 "\n"
                 "Flow:\n"
                 "  1. Paste the OFFER generated by the client (rtcsocks), or read it\n"
                 "     automatically via --offer-file\n"
                 "  2. This program generates the ANSWER; send it back to the client\n"
                 "  3. Once the P2P link is up, this side acts as the exit and proxies\n"
                 "     the TCP/UDP connections requested by the client\n"
                 "\n"
                 "Options:\n"
                 "  -S, --stun <host[:port]> STUN server, required on BOTH sides across NAT\n"
                 "                           (default: none, host candidates only)\n"
                 "  -t, --threads <n>        asio IO thread count (default %d)\n"
                 "      --offer-file <path>  poll this file for the OFFER (instead of stdin)\n"
                 "      --answer-file <path> also write the ANSWER to this file\n"
                 "      --wait <sec>         timeout in seconds when waiting for the offer\n"
                 "                           file (default %d)\n"
                 "      --log-level <level>  log level: verbose|debug|info|warning|error|none\n"
                 "                           (default info)\n"
                 "  -h, --help               show this help\n"
                 "  -V, --version            show version\n"
                 "\n"
                 "Notes:\n"
                 "  - There is no password: the SDP itself is the credential, keep it private.\n"
                 "  - Press q in the terminal (or Ctrl+C) to quit.\n",
                 kProgramName, kVersion, kProgramName,
                 kDefaultThreadCount, kDefaultWaitSec);
}

void printVersion()
{
    std::fprintf(stdout, "%s %s\n", kProgramName, kVersion);
}

bool splitInlineValue(std::string &arg, std::string &value)
{
    if (arg.rfind("--", 0) == 0)
    {
        auto eq = arg.find('=');
        if (eq != std::string::npos)
        {
            value = arg.substr(eq + 1);
            arg = arg.substr(0, eq);
            return true;
        }
    }
    return false;
}

bool parseU16(const std::string &s, uint16_t &out)
{
    if (s.empty() || s.find_first_not_of("0123456789") != std::string::npos)
        return false;

    long v = std::strtol(s.c_str(), nullptr, 10);
    if (v < 1 || v > 65535)
        return false;

    out = static_cast<uint16_t>(v);
    return true;
}

bool parseThreads(const std::string &s, int &out)
{
    if (s.empty() || s.find_first_not_of("0123456789") != std::string::npos)
        return false;

    long v = std::strtol(s.c_str(), nullptr, 10);
    if (v < 1 || v > 64)
        return false;

    out = static_cast<int>(v);
    return true;
}

bool parseWaitSec(const std::string &s, int &out)
{
    if (s.empty() || s.find_first_not_of("0123456789") != std::string::npos)
        return false;

    long v = std::strtol(s.c_str(), nullptr, 10);
    if (v < 1 || v > 86400)
        return false;

    out = static_cast<int>(v);
    return true;
}

bool parseStun(const std::string &in, std::string &host, uint16_t &port)
{
    std::string s = in;
    if (s.rfind("stun://", 0) == 0)
        s = s.substr(7);
    else if (s.rfind("stun:", 0) == 0)
        s = s.substr(5);

    if (s.empty())
        return false;

    auto colon = s.rfind(':');
    if (colon != std::string::npos)
    {
        std::string p = s.substr(colon + 1);
        if (!p.empty() && p.find_first_not_of("0123456789") == std::string::npos)
        {
            uint16_t v = 0;
            if (!parseU16(p, v))
                return false;
            host = s.substr(0, colon);
            port = v;
            return !host.empty();
        }
    }

    host = s;
    port = 3478;
    return true;
}

bool parseLogLevel(const std::string &s, rtc::LogLevel &rtc_level)
{
    if (s == "verbose") { rtc_level = rtc::LogLevel::Verbose; return true; }
    if (s == "debug")   { rtc_level = rtc::LogLevel::Debug;   return true; }
    if (s == "info")    { rtc_level = rtc::LogLevel::Info;    return true; }
    if (s == "warning") { rtc_level = rtc::LogLevel::Warning; return true; }
    if (s == "error")   { rtc_level = rtc::LogLevel::Error;   return true; }
    if (s == "none")    { rtc_level = rtc::LogLevel::None;    return true; }
    return false;
}

ParseResult parseArgs(int argc, char *argv[], Options &opts, std::string &error)
{
    for (int i = 1; i < argc; ++i)
    {
        std::string arg = argv[i];
        std::string inline_value;
        bool has_inline = splitInlineValue(arg, inline_value);

        auto value = [&](const char *opt) -> const char *
        {
            if (has_inline)
                return inline_value.c_str();
            if (i + 1 >= argc)
            {
                error = std::string("option ") + opt + " requires a value";
                return nullptr;
            }
            return argv[++i];
        };

        if (arg == "-h" || arg == "--help")
        {
            printUsage(stdout);
            return ParseResult::Handled;
        }
        else if (arg == "-V" || arg == "--version")
        {
            printVersion();
            return ParseResult::Handled;
        }
        else if (arg == "-S" || arg == "--stun")
        {
            const char *v = value("--stun");
            if (!v) return ParseResult::Error;
            if (!parseStun(v, opts.stun_host, opts.stun_port))
            {
                error = std::string("invalid STUN address: ") + v + " (expected host[:port])";
                return ParseResult::Error;
            }
        }
        else if (arg == "-t" || arg == "--threads")
        {
            const char *v = value("--threads");
            if (!v) return ParseResult::Error;
            if (!parseThreads(v, opts.threads))
            {
                error = std::string("invalid thread count: ") + v + " (expected 1-64)";
                return ParseResult::Error;
            }
        }
        else if (arg == "--offer-file")
        {
            const char *v = value("--offer-file");
            if (!v) return ParseResult::Error;
            opts.offer_file = v;
        }
        else if (arg == "--answer-file")
        {
            const char *v = value("--answer-file");
            if (!v) return ParseResult::Error;
            opts.answer_file = v;
        }
        else if (arg == "--wait")
        {
            const char *v = value("--wait");
            if (!v) return ParseResult::Error;
            if (!parseWaitSec(v, opts.wait_sec))
            {
                error = std::string("invalid wait seconds: ") + v;
                return ParseResult::Error;
            }
        }
        else if (arg == "--log-level")
        {
            const char *v = value("--log-level");
            if (!v) return ParseResult::Error;
            if (!parseLogLevel(v, opts.log_level))
            {
                error = std::string("invalid log level: ") + v +
                        " (expected verbose|debug|info|warning|error|none)";
                return ParseResult::Error;
            }
        }
        else if (!arg.empty() && arg[0] == '-')
        {
            error = "unknown option: " + arg;
            return ParseResult::Error;
        }
        else
        {
            error = "unexpected argument: " + arg;
            return ParseResult::Error;
        }
    }

    return ParseResult::Ok;
}

void input_keyboard()
{
    char c;

    while (running)
    {
        if (!isStdinTerminal())
        {
            std::this_thread::sleep_for(std::chrono::seconds(2));
            continue;
        }
        else
        {
            std::cin.get(c);
            if (c == 'q' || c == 'Q')
            {
                PLOG_INFO << "input q, exit";

                running = false;
                break;
            }
        }
    }
    PLOG_INFO << "input keyboard exit";
}

} // namespace

int main(int argc, char *argv[])
{
    Options opts;
    std::string parse_error;

    switch (parseArgs(argc, argv, opts, parse_error))
    {
    case ParseResult::Handled:
        return 0;
    case ParseResult::Error:
        std::fprintf(stderr, "Error: %s\n\n", parse_error.c_str());
        printUsage(stderr);
        return 1;
    case ParseResult::Ok:
    default:
        break;
    }

    CrashDump::InstallCrashHandler("");

    // PLOG_* 与 rtc 日志共用一条通道: rtc::InitLogger 内部初始化 plog 实例并回调
    // rtcLogCallback (写入 rtc_exit.log 并输出到控制台)
    RtcLogger::instance().init("rtc_exit.log");
    rtc::InitLogger(opts.log_level, rtcLogCallback);

    std::signal(SIGINT, signal_handler);
    std::signal(SIGTERM, signal_handler);

    PLOG_INFO << kProgramName << " " << kVersion << " start";

    PLOG_INFO << "stun: " << (opts.stun_host.empty() ? "<none, host candidates only>"
                                                     : opts.stun_host + ":" + std::to_string(opts.stun_port));
    if (!opts.offer_file.empty())
    {
        PLOG_INFO << "offer file: " << opts.offer_file;
    }
    if (!opts.answer_file.empty())
    {
        PLOG_INFO << "answer file: " << opts.answer_file;
    }

    asio::io_context io;
    // 防止 io.run() 因为暂时没有任务而直接退出
    auto work_guard = asio::make_work_guard(io);

    std::vector<std::thread> io_threads;
    for (int i = 0; i < opts.threads; i++)
    {
        io_threads.emplace_back([&io]()
                                {
            try
            {
                io.run();
            }
            catch (const std::exception &e)
            {
                PLOG_ERROR << "io thread exception: " << e.what();
            } });
    }

    // ---------- 业务接线：P2P 数据通道 <-> 会话复用器 <-> 出口连接 ----------
    p2psocks::SessionMux mux(1);
    std::mutex tunnels_mutex;
    std::unordered_map<uint32_t, std::shared_ptr<TunnelSession>> tunnel_sessions;

    ManualP2P p2p;
    rtc::Configuration rtc_config;
    if (!opts.stun_host.empty())
        rtc_config.iceServers.push_back({opts.stun_host, opts.stun_port});
    p2p.init(rtc_config);

    p2p.onData([&mux](const uint8_t *data, size_t len)
               {
        auto result = p2psocks::unpackMessage(reinterpret_cast<const std::byte *>(data), len);
        if (result)
            mux.on_p2p_data(1, result->payload, result->len);
        else
            PLOG_ERROR << "unpackMessage failed"; });

    mux.set_send_func([&p2p](uint32_t, const uint8_t *data, size_t len)
                      {
        try
        {
            auto buf = p2psocks::packMessage(data, len);
            p2p.send(reinterpret_cast<const uint8_t *>(buf.data()), buf.size());
        }
        catch (const std::length_error &e)
        {
            PLOG_ERROR << "packMessage: " << e.what();
        } });

    mux.set_on_syn([&](uint32_t stream_id, const std::string &host, uint16_t port, Protocol protocol)
                   {
        PLOG_INFO << "exit connect " << host << ":" << port
                  << " (stream_id=" << stream_id << ")";
        auto rs = std::make_shared<TunnelSession>(io, mux, stream_id, protocol);
        {
            std::lock_guard<std::mutex> lock(tunnels_mutex);
            tunnel_sessions[stream_id] = rs;
        }
        rs->bind_close_func([&](uint32_t sid)
                            {
            PLOG_DEBUG << "tunnel_sessions_ erase " << sid;
            std::lock_guard<std::mutex> lock(tunnels_mutex);
            tunnel_sessions.erase(sid); });
        rs->start(host, port); });

    p2p.onConnected([]()
                    { PLOG_INFO << "P2P connected, ready to proxy"; });

    p2p.onClosed([&]()
                 {
        PLOG_INFO << "p2p closed, closing all tunnels";
        {
            std::lock_guard<std::mutex> lock(tunnels_mutex);
            for (auto &t : tunnel_sessions)
                t.second->close();
            tunnel_sessions.clear();
        }

        running = false; });

    // ---------- 第 1 步：获取 OFFER ----------
    std::string offer_b64;
    if (!opts.offer_file.empty())
    {
        PLOG_INFO << "waiting for offer file: " << opts.offer_file;
        offer_b64 = ReadSdpFromFile(opts.offer_file, opts.wait_sec);
    }
    else
    {
        offer_b64 = ReadSdpFromStdin("the OFFER block generated by the client");
    }

    if (offer_b64.empty())
    {
        PLOG_ERROR << "no valid offer";
        return 1;
    }

    // ---------- 第 2 步：生成 ANSWER ----------
    std::string answer_b64 = p2p.acceptOffer(offer_b64, kGatherTimeoutSec);
    if (answer_b64.empty())
    {
        PLOG_ERROR << "create answer failed";
        return 1;
    }
    PrintSdp("ANSWER", answer_b64);
    std::cout << "Send the ANSWER above back to the client (rtcsocks)" << std::endl;
    if (!opts.answer_file.empty())
        WriteSdpToFile(opts.answer_file, answer_b64);

    PLOG_INFO << "waiting for p2p connected... (input q to exit)";

    input_keyboard();

    PLOG_INFO << "closing ...";

    p2p.close();

    {
        std::lock_guard<std::mutex> lock(tunnels_mutex);
        for (auto &t : tunnel_sessions)
            t.second->close();
        tunnel_sessions.clear();
    }

    work_guard.reset();

    for (auto &t : io_threads)
    {
        if (t.joinable())
            t.join();
    }

    RtcLogger::instance().shutdown();

    return 0;
}
